name: atom_admin
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  supabase: ^1.9.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  loader_overlay: ^2.2.0
  flutter_svg: ^2.0.5
  meta: ^1.8.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

flutter_launcher_icons:
  image_path_android: "assets/icons/logo.png"
  image_path_ios: "assets/icons/logo.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "assets/icons/logo.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/icons/logo.png" # only available for Android 8.0 devices and above
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"